// Jest provides globalThis.test. When this file is run directly with
// `node --test`, fall back to Node's built-in test function.
const test=globalThis.test??require('node:test').test;
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const M=require('../dist/state.js');
function memory(){const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};}
function setup(){const storage=memory(),s=M.createStore(storage);return {s,storage,id:s.db.applications[0].id};}
const schedule=(id,extra={})=>({applicationId:id,date:M.day(2),time:'10:00',duration:60,format:'Video',location:'Meeting link provided separately',interviewer:'Sarah Mitchell',notify:true,...extra});

test('initial counts match the workflow design and all references are valid',()=>{const d=M.seed();assert.ok(M.validate(d));assert.equal(d.applications.length,115);assert.deepEqual(Object.fromEntries(['Offer','Pending Review','Rejected','Interview Results'].map(s=>[s,d.applications.filter(a=>a.stage===s).length])),{Offer:18,'Pending Review':42,Rejected:31,'Interview Results':24});});
test('review to interview updates stage, timeline and one unsent draft; persists after reload',()=>{const {s,storage,id}=setup();const result=s.commit('move-interview',{applicationId:id,notes:'Review API design',notify:true});assert.equal(s.db.applications[0].stage,'Interview');assert.equal(s.db.notifications[0].status,'Draft');assert.equal(s.db.notifications.length,1);assert.equal(result.activity.notes,'Review API design');assert.equal(M.createStore(storage).db.applications[0].stage,'Interview');});
test('repeated transitions are rejected without changing saved state',()=>{const {s,id}=setup();s.commit('move-interview',{applicationId:id});const snapshot=JSON.stringify(s.db);assert.throws(()=>s.commit('move-interview',{applicationId:id}),/not available/);assert.equal(JSON.stringify(s.db),snapshot);});
test('blank rejection reason is blocked and does not partially mutate data',()=>{const {s,id}=setup();const before=JSON.stringify(s.db);assert.throws(()=>s.commit('reject',{applicationId:id,reason:'  '}),/required/);assert.equal(JSON.stringify(s.db),before);});
test('rejection cancels scheduled interviews; internal notes do not leak into email',()=>{const {s,id}=setup();s.commit('move-interview',{applicationId:id});s.commit('schedule',schedule(id));s.commit('reject',{applicationId:id,reason:'Skills gap',notes:'INTERNAL-PRIVATE',notify:true});assert.equal(s.db.applications[0].stage,'Rejected');assert.equal(s.db.interviews.find(i=>i.applicationId===id).status,'Cancelled');assert.ok(!s.db.notifications[0].body.includes('INTERNAL-PRIVATE'));});
test('notification-off saves no email draft',()=>{const {s,id}=setup();s.commit('reject',{applicationId:id,reason:'Skills gap',notify:false});assert.equal(s.db.notifications.length,0);});
test('scheduling before interview stage and past dates are blocked',()=>{const {s,id}=setup();assert.throws(()=>s.commit('schedule',schedule(id)),/Interview/);s.commit('move-interview',{applicationId:id});assert.throws(()=>s.commit('schedule',schedule(id,{date:M.day(-1)})),/future/);});
test('interviewer and room overlaps are blocked, adjacent appointments allowed',()=>{const {s,id}=setup();const second=s.db.applications.find(a=>a.stage==='Pending Review'&&a.id!==id).id;s.commit('move-interview',{applicationId:id});s.commit('move-interview',{applicationId:second});s.commit('schedule',schedule(id,{format:'On-site',location:'Room A'}));assert.throws(()=>s.commit('schedule',schedule(second,{time:'10:30'})),/overlaps/);assert.throws(()=>s.commit('schedule',schedule(second,{time:'10:30',format:'On-site',location:'Room A',interviewer:'Another reviewer'})),/overlaps/);assert.doesNotThrow(()=>s.commit('schedule',schedule(second,{time:'11:00'})));});
test('reschedule updates the booking and supersedes the old schedule draft',()=>{const {s,id}=setup();s.commit('move-interview',{applicationId:id});const r=s.commit('schedule',schedule(id));const oldNotice=s.db.notifications[0].id;s.commit('schedule',schedule(id,{interviewId:r.interview.id,time:'12:00'}));assert.equal(s.db.interviews.filter(i=>i.applicationId===id).length,1);assert.equal(s.db.interviews.find(i=>i.applicationId===id).time,'12:00');assert.equal(s.db.notifications.find(n=>n.id===oldNotice).status,'Superseded');});
test('completed feedback moves a past interview into results',()=>{const {s,id}=setup();s.commit('move-interview',{applicationId:id});const r=s.commit('schedule',schedule(id));const data=M.clone(s.db);data.interviews.find(i=>i.id===r.interview.id).date=M.day(-1);s.restore(data);s.commit('feedback',{applicationId:id,interviewId:r.interview.id,rating:4,recommendation:'Proceed',notes:'Strong technical skills'});assert.equal(s.db.applications[0].stage,'Interview Results');assert.equal(s.db.interviews.find(i=>i.id===r.interview.id).status,'Completed');});
test('future interview feedback is blocked',()=>{const {s,id}=setup();s.commit('move-interview',{applicationId:id});const r=s.commit('schedule',schedule(id));assert.throws(()=>s.commit('feedback',{applicationId:id,interviewId:r.interview.id,rating:4,recommendation:'Proceed',notes:'Feedback'}),/after/);});
test('offer requires results, valid salary and coherent dates',()=>{const {s,id}=setup();assert.throws(()=>s.commit('offer',{applicationId:id}),/results/);const resultId=s.db.applications.find(a=>a.stage==='Interview Results').id;assert.throws(()=>s.commit('offer',{applicationId:resultId,salary:-1,startDate:M.day(30),expiry:M.day(7),terms:'Terms'}),/salary/);assert.throws(()=>s.commit('offer',{applicationId:resultId,salary:5000,startDate:M.day(2),expiry:M.day(7),terms:'Terms'}),/start date/);});
test('offer approval, notification and acceptance form a coherent flow',()=>{const {s}=setup();const id=s.db.applications.find(a=>a.stage==='Interview Results').id;s.commit('offer',{applicationId:id,salary:5500,startDate:M.day(30),expiry:M.day(7),terms:'Standard benefits'});assert.throws(()=>s.commit('offer-message',{applicationId:id}),/Approve/);s.commit('approve-offer',{applicationId:id});s.commit('offer-message',{applicationId:id});assert.throws(()=>s.commit('offer-message',{applicationId:id}),/already/);s.commit('accept-offer',{applicationId:id,notes:'Candidate confirmed by phone'});assert.equal(s.db.applications.find(a=>a.id===id).stage,'Hired');});
test('closed job blocks progression and rescheduling but preserves applicants',()=>{const {s,id}=setup();const jobId=s.db.applications[0].jobId;s.commit('job-status',{id:jobId,status:'Closed'});assert.equal(s.db.applications.length,115);assert.throws(()=>s.commit('move-interview',{applicationId:id}),/Activate/);s.commit('job-status',{id:jobId,status:'Active'});s.commit('move-interview',{applicationId:id});s.commit('job-status',{id:jobId,status:'Closed'});assert.throws(()=>s.commit('schedule',schedule(id)),/active/);});
test('task completion is recorded and cannot be duplicated',()=>{const {s,id}=setup();s.commit('task',{applicationId:id,title:'Prepare questions',assignee:'Sarah',due:M.day(1)});const t=s.db.tasks[0];s.commit('complete-task',{id:t.id});assert.equal(s.db.tasks[0].status,'Completed');assert.throws(()=>s.commit('complete-task',{id:t.id}),/already/);});
test('storage failure does not report unsaved changes as committed',()=>{const {s,storage,id}=setup();storage.setItem=()=>{throw Error('Quota exceeded');};assert.throws(()=>s.commit('move-interview',{applicationId:id}),/not saved/);assert.equal(s.db.applications[0].stage,'Pending Review');});
test('concurrent-tab edits are detected instead of overwriting them',()=>{const {s,storage,id}=setup();const other=M.createStore(storage);other.commit('move-interview',{applicationId:id});assert.throws(()=>s.commit('reject',{applicationId:id,reason:'Skills gap'}),/another tab/);});
test('corrupt backups and foreign references are rejected',()=>{const {s,storage}=setup();const value=M.clone(s.db);value.applications[0].jobId='missing';assert.throws(()=>s.restore(value),/not found/);storage.setItem(M.KEY,'not-json');const broken=M.createStore(storage);assert.ok(broken.error);assert.equal(broken.raw,'not-json');assert.throws(()=>broken.commit('read-all'),/Saved data/);});
test('all page templates render from shared data and escape imported/user text',()=>{
  const context={console,Blob,HRModel:M,window:{}};context.window=context;vm.createContext(context);for(const f of ['icons.js','resume.js','views.js'])vm.runInContext(fs.readFileSync(require.resolve('../dist/'+f),'utf8'),context);
  const d=M.seed(),a=d.applications[0],ui={page:1,q:'',job:'',stage:'',priority:'',from:'',to:'',full:false,period:'today',resumePage:1,zoom:90,jobStatus:'',interviewStatus:'',interviewDate:'',noticeTab:'all'};
  for(const route of [['dashboard'],['applications'],['review',a.id],['candidates'],['candidate',a.candidateId],['jobs'],['interviews'],['reports'],['notifications']])assert.ok(context.HRViews.render(route,d,{...ui}).length>100,route.join('/'));
  const update=M.apply(d,'move-interview',{applicationId:a.id,notify:true,notes:'Review API knowledge'});const success=context.HRViews.render(['success',update.activity.id],d,{...ui});assert.ok(success.includes('Notification added to outbox'));assert.ok(success.includes('It has not been sent.'));assert.equal(update.activity.notificationId,update.notification.id);assert.ok(context.HRViews.button('close','Cancel').includes('type="button"'));
  d.candidates[0].name='<script>alert(1)</script>';const html=context.HRViews.render(['candidate',a.candidateId],d,{...ui});assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));
});
